### ISSUE TITLE
Change default size of all icons?

### ISSUE THREAD

**Issue by bekicot** [feathericons/elm-feather#16]
Can we change the default size of all icons?

For example:
```elm
FeatherIcons.hash
                    |> FeatherIcons.withSize 18
```
and set the default size to 18, we don't need the:
```elm
FeatherIcons.withSize 18
```

If it is already there, please close this issue. I'm new to elm and have a lot of things to learn, I probably missed it

**Comment by 1602** [comment]
All functions in elm are pure, so it is not possible have a side effect you want by setting a global variable. In javascript would be possible to have the API you are talking about, but not in elm.

If you want all icons to be the same size, create a function which will be calling `FeatherIcons.withSize 18`.
