### ISSUE TITLE
Error with 0.19

### ISSUE THREAD

**Issue by David-Factor** [feathericons/elm-feather#9]
Thanks for the great library. I really love the API!

Just installed this in a 0.19 project. I get the following error in the console: `SyntaxError: identifier starts immediately after numeric literal`

Digging a little deeper it seems the offending line in the compiled js is:
```
var 1602$elm_feather$FeatherIcons$Icon = function (a) {
	return {$: 'Icon', a: a};
};
```

Looks like 0.19 assigns your name as a variable. Given that your name is a numeric literal, the js borks.
For  details about why this is illegal in js, see:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number

Not sure what the solution is other than republishing this package under another namespace?

Cheers,
Dave

**Comment by ryan-senn** [comment]
If anyone is looking for a workaround, this is what I'm doing at the moment:

- Download the source file : https://raw.githubusercontent.com/1602/elm-feather/master/src/FeatherIcons.elm
- Put it into your `src` folder
- add the following dependencies:
    ```
    elm install elm/core
    elm install elm/html
    elm install elm/json
    elm install elm/svg
    elm install elm/virtual-dom
    ```
- remove `1602/elm-feather` from your elm.json file

And it should be working. Just remember to check back every now and then and undo all of the above!

**Comment by 1602** [comment]
elm-feather has now moved to feathericons GH org and elm package published under a new name: [feathericons/elm-feather](https://package.elm-lang.org/packages/feathericons/elm-feather/latest/)
